### ISSUE TITLE
Statamic 3.1 GraphQL

### ISSUE THREAD

**Issue by jasonvarga** [robertguss/gatsby-source-statamic#8]
This is not really an issue, but I wanted to ask for your feedback on Statamic's new GraphQL implementation.

https://statamic.com/blog/statamic-3.1-preview

We'd love to hear what you think. Maybe it makes this Gatsby plugin better to use GraphQL rather than REST.

**Comment by robertguss** [comment]
This will make things so much easier and better. I can't wait to test it out. Thanks for letting me know Jason :)

**Comment by robertguss** [comment]
@jasonvarga I finally got around to trying this out. My wife and I just had a baby so I have been away for a few weeks. I didn't realize this was a pro feature. I don't have a pro license yet, but if I get around to purchasing one I will be sure to make this plugin.

**Comment by jasonvarga** [comment]
Congratulations on the baby! 🍾 🍼 👶 🎉  

The REST API is a pro feature too, which you're using already anyway. You don't need to buy the license to use it though. Only for production.

**Comment by robertguss** [comment]
Thank you. Ahh my bad. I had some trouble getting it working, but I will figure it out. Thanks again.

**Comment by robertguss** [comment]
@jasonvarga Hey Jason. So I found this plugin already, which is made by the Gatsby team and it works just fine with the new Statamic GraphQL API: https://www.gatsbyjs.com/plugins/gatsby-source-graphql/

No need to re-invent the wheel, so maybe when the API is fully released you could add this to your docs?

**Comment by jasonvarga** [comment]
Did you create a project to test this out? Would you be able to share it? (Privately, if you prefer.)

**Comment by robertguss** [comment]
I did, but then I deleted it  :(

If you want I can create a demo gatsby site that queries one of the statamic starter kits if you want to play around with it?

**Comment by robertguss** [comment]
Here is a demo repo that has everything you should need to test it out: https://github.com/robertguss/statamic-gatsby-graphql

You will need to make a new user to log into the cp if you want to.

You will need to `npm i` inside of the gatsby folder to install all the modules. If you look in `gatsby-config.js` you will see the URL that I am using for the statamic starters creek site. You may need to change this depending upon your setup. Then you can run `npm run develop` to start the Gatsby dev server and then navigate to: 

http://localhost:8000/___graphql

And here is a sample query to see the blog posts

```js
query MyQuery {
  statamic {
    entries {
      total
      data {
        title
        ... on Statamic_Entry_Blog_Blog {
          main_content {
            ... on Statamic_BardText {
              text
            }
          }
        }
      }
    }
  }
}
```

all of the statamic content lives in the graphiql explorer under `statamic`. I hope this helps.

**Comment by jasonvarga** [comment]
Thanks! I can see the data on the ___graphql endpoint. 👍 

To be honest I'm not super familiar with Gatsby, but isn't there a benefit to a dedicated source plugin?
Why don't all those other CMSs with GraphQL APIs just use the GraphQL source plugin too?

**Comment by robertguss** [comment]
You bring up a very good point, that I didn't consider. I think the main benefit is how specific it is for the cms and the various options and configs you can utilize. 

I will take a look at some others and see what I can come up with. If it will help you guys I am all for it. 

I also am not a super familiar with Gatsby to be honest. I use Vue. I made the other plugin because Gatsby is such a big player in the jamstack space and I wanted Statamic to be in there. I also told Jack I would, and I try to be a man of my word. 

I will keep you posted. Thanks Jason

**Comment by jasonvarga** [comment]
I didn't mean to come across as nudging you to do any more work than you want to. I was just curious! 😄 

I'll likely be building an example site for me and everyone else to learn from. Hopefully I'll discover what a dedicated source plugin would bring to the table. Maybe it's not even necessary.

I appreciate all the help here. Thanks! You can close this if you want.

**Comment by robertguss** [comment]
Oh not at all. I didn't get that impression from you, so no worries. 

I enjoy doing this kind of stuff so I will see what I can come up with. I also think having a dedicated plugin will help with marketing and people finding it to use it. I am not sure if you have seen this: https://snipcart.com/blog/statamic-headless-gatsby-blog-tutorial but having a dedicated plugin will help for content creators too I would imagine. I don't think most people will be searching for a generic GraphQL plugin for Gatsby rather they will search for the keyword "statamic."

I also just really like what you guys at Statamic are doing so if I can help in any way I am more than happy too. I will be in touch if I come up with something for the plugin.
